#:kivy 1.11.1

<GameScreen>:

    FloatLayout:
        pos: 0, 0
        size: root.width, root.height

        
        Label:
            text: 'Here is some text in a label'
            pos_hint: {'x': .1, 'y': .9}
            size_hint: .8, .1
            halign: 'left'
            text_size: self.size
            font_size: 50
            bold: True
            color: 0, 1, 0, 1
